### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by ifanshx** [wdserverr/airdrop-mavia#1]
Saya mau tanya bang ambil Datanya itu gimana dan dimana ya bang mohon pencerahanya saya mau pake script ini karena wallet saya terkena drain dan saya mau coba adu bot. trimakasih banyak bang

**Comment by wdserverr** [comment]
ambil data disini bang, cek di popup metamask nya

![image](https://github.com/wdserverr/airdrop-mavia/assets/42107311/eb435a27-2f37-4a26-98eb-e227292dca26)
